name: Build, test and publish the image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        run: docker build -t platform-docs-redirect-test .
      
      - name: Run container
        run: |
          docker run -d -p 2015:2015 -p2016:2016 --name redirect-container platform-docs-redirect-test
      
      - name: Wait for healthy container
        run: |
          for i in {1..5}; do
            health=$(docker inspect --format='{{.State.Health.Status}}' redirect-container)
            if [[ "$health" = "healthy" ]]; then
              echo "Container is healthy!"; exit 0
            fi
            echo "Waiting for container to become healthy... ($i/5)"
            sleep 30
          done
          echo "Container did not become healthy in time." && docker logs redirect-container && exit 1
      
      - name: Run tests
        run: |
          chmod +x ./scripts/test-redirects.sh
          ./scripts/test-redirects.sh localhost 2015
      
      - name: Stop container
        if: always()
        run: docker stop redirect-container

  publish:
    name: Publish to GitHub Container Registry
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor}}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: latest=true
          tags: |
            type=sha,format=short
      
      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v6.17.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
