name: Build, test and publish the image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        run: docker build -t platform-docs-redirect-test .
      
      - name: Run container
        run: |
          docker run -d -p 2015:2015 --name redirect-container platform-docs-redirect-test
          # Wait for container to start
          for i in {1..10}; do
            if curl -sSf http://localhost:2015/ > /dev/null; then
              echo "Caddy is up!"; break
            fi
            echo "Waiting for Caddy to be ready... ($i/10)"; sleep 2
          done
      
      - name: Check container is running
        run: docker ps | grep redirect-container
      
      - name: Run tests
        run: |
          chmod +x ./scripts/test-redirects.sh
          ./scripts/test-redirects.sh localhost 2015
      
      - name: Stop container
        if: always()
        run: docker stop redirect-container

  publish:
    name: Publish to GitHub Container Registry
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=sha,prefix=,format=short
            type=raw,value=latest,enable=true
      
      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v6.17.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
